GET http://localhost:3000/auth/1


### Find all users
GET http://localhost:3000/auth

### Signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test1234@test.com",
  "password": "12345656"
}

### Signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test1234@test.com",
  "password": "12345656"
}

### Set color
GET http://localhost:3000/auth/colors/red

### Get color
GET http://localhost:3000/auth/colors

### Get current user
GET http://localhost:3000/auth/whoami